/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.wh162.battleship;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.io.Reader;

public class App {

  private final Board<Character> theBoard;
  private final BoardTextView view;
  private final BufferedReader inputReader;
  private final PrintStream out;

  /**
   * A Constructor for the APP
   */
  public App(Board<Character> theBoard, Reader inputSource, PrintStream out) {
    this.theBoard = theBoard;
    this.view = new BoardTextView(theBoard);
    this.inputReader = new BufferedReader(inputSource);
    this.out = out;
  }

  public Placement readPlacement(String prompt) throws IOException {
    out.println(prompt);
    String s = inputReader.readLine();
    return new Placement(s);
  }

  /**
   * create a doOnePlacement method which does
   * read a PlXoacement
   * Create a basic ship based on the location in that Placement
   * Add that ship to the Board
   * Print out the board (to out, not to System.out)
   */
  public void doOnePlacement() throws IOException{
    Placement p = readPlacement("Where would you like to put your ship?");
    Ship<Character> s = new BasicShip(p.getWhere());
    theBoard.tryAddShip(s);
    out.println(view.displayMyOwnBoard());
  }

  public static void main(String[] args) throws IOException {
    Board<Character> b = new BattleShipBoard<Character>(10, 20);
    Reader r  = new InputStreamReader(System.in);
    App app = new App(b, r, System.out);
    app.doOnePlacement();
  }
}
