/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.wh162.battleship;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;

/**
 * This is the class where we start our game
 * by creating two players and let them start the game
 * for now it's just only two players
 * */
public class App {

  private  TextPlayer p1;
  private  TextPlayer p2;

  /**
   * Constructor for the two players
   */
  public App(TextPlayer p1, TextPlayer p2) {
    this.p1 = p1;
    this.p2 = p2;
  }

  /**
   * state each player the correct placement to do
   */
  public void doPlacementPhase() throws IOException{
     p1.doPlacementPhase();
     p2.doPlacementPhase();
   }

   /**
   * Check which player wins the game of lose the game
   */
  public void doAttackingPhase() throws IOException {
    while (true) {
      p1.playOneTurn(p2.theBoard, p2.getName());
      if (p2.checkLose() == true) {
        System.out.println("----------------------------------------------------------\n" + "Congratulations! Player " + p1.getName() + " you win!");
        break;
      }
      p2.playOneTurn(p1.theBoard, p1.getName());
      if (p1.checkLose() == true) {
        System.out.println("----------------------------------------------------------\n" + "Congratulations! Player " + p2.getName() + " you win!");
        break;
      }
    }
  }
  
  /**
   * Main function of the whole program
   * We will make changes in this part to 
   * enable different modes of gaming
   */
  public static void main(String[] args) throws IOException {
    Board<Character> b1 = new BattleShipBoard<Character>(10, 20, 'X');
    Board<Character> b2 = new BattleShipBoard<Character>(10, 20, 'X');
    InputStreamReader input = new InputStreamReader(System.in);
    BufferedReader br = new BufferedReader(input);
    PrintStream out = System.out;
    //V1ShipFactory sf = new V1ShipFactory();
    V2ShipFactory sf = new V2ShipFactory();

    TextPlayer p1 = new TextPlayer("A", b1, br, out, sf);
    TextPlayer p2 = new TextPlayer("B", b2, br, out, sf);
    App a = new App(p1, p2);
    a.doPlacementPhase();
    a.doAttackingPhase();
  }
}
